# Generated by Django 6.0.2 on 2026-03-31 17:55

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('HAND_HYGIENE', 'Hand hygiene'), ('PATIENT_IDENTIFICATION', 'Patient identification'), ('PAIN_ASSESSMENT', 'Pain assessment'), ('VITAL_SIGNS', 'Vital signs (manual + electronic)'), ('OXYGEN_SATURATION', 'Oxygen saturation'), ('COMPREHENSIVE_HTT_ASSESSMENT', 'Comprehensive head-to-toe assessment'), ('FOCUSED_ASSESSMENTS', 'Focused assessments'), ('FALL_RISK_ASSESSMENT', 'Fall risk assessment'), ('SKIN_ASSESSMENT', 'Skin assessment / pressure injury staging'), ('NEURO_CHECKS', 'Neuro checks'), ('IO_CALCULATION', 'Intake & output calculation'), ('ACCURATE_DOCUMENTATION', 'Accurate documentation'), ('PPE_DONNING_DOFFING', 'PPE donning/doffing'), ('STERILE_TECHNIQUE', 'Sterile technique'), ('ISOLATION_PRECAUTIONS', 'Isolation precautions'), ('SHARPS_SAFETY', 'Sharps safety'), ('MEDICATION_SAFETY_CHECKS', 'Medication safety checks'), ('BED_SAFETY_ALARMS', 'Bed safety / alarms'), ('SAFE_PATIENT_ENVIRONMENT_SCAN', 'Safe patient environment scan'), ('BED_BATH_HYGIENE', 'Bed bath / hygiene'), ('ORAL_CARE_DEPENDENT_PATIENT', 'Oral care (including dependent patient)'), ('FEEDING_ASSISTANCE', 'Feeding assistance'), ('SAFE_PATIENT_HANDLING', 'Safe patient handling'), ('TRANSFERS_GAIT_BELT', 'Transfers (gait belt)'), ('MECHANICAL_LIFTS', 'Mechanical lifts (demo acceptable)'), ('POSITIONING_PRESSURE_PREVENTION', 'Positioning & pressure prevention'), ('BEDMAKING', 'Bedmaking (occupied/unoccupied)'), ('SIX_RIGHTS_THREE_CHECKS', 'Six rights + three checks'), ('ORAL_MEDS', 'Oral meds'), ('LIQUID_MEDS', 'Liquid meds'), ('IM_INJECTIONS', 'IM injections'), ('SUBCUTANEOUS_INJECTIONS', 'Subcutaneous injections (incl. insulin)'), ('MEDICATION_RECONCILIATION', 'Medication reconciliation'), ('BARCODE_SCANNING', 'Barcode scanning'), ('MEDICATION_PATIENT_EDUCATION', 'Patient education for meds'), ('BEDPAN_URINAL', 'Bedpan / urinal'), ('FOLEY_INSERTION', 'Foley catheter insertion'), ('FOLEY_CARE', 'Foley care'), ('SPECIMEN_COLLECTION', 'Specimen collection'), ('BLADDER_SCAN', 'Bladder scan'), ('OSTOMY_CARE', 'Ostomy care'), ('ENEMA', 'Enema'), ('NASAL_CANNULA', 'Nasal cannula'), ('SIMPLE_MASK', 'Simple mask'), ('INCENTIVE_SPIROMETRY', 'Incentive spirometry'), ('PULSE_OX_INTERPRETATION', 'Pulse ox interpretation'), ('COUGH_DEEP_BREATHE_COACHING', 'Cough/deep breathe coaching'), ('IV_PUMP_PROGRAMMING', 'IV pump programming'), ('PRIMARY_TUBING_SETUP', 'Primary tubing setup'), ('IV_SITE_ASSESSMENT', 'IV site assessment'), ('PERIPHERAL_IV_REMOVAL', 'Peripheral IV removal'), ('NG_TUBE_CARE', 'NG tube care'), ('SBAR_COMMUNICATION', 'SBAR communication'), ('THERAPEUTIC_COMMUNICATION', 'Therapeutic communication'), ('CULTURAL_HUMILITY', 'Cultural humility'), ('INFORMED_CONSENT_AWARENESS', 'Informed consent awareness'), ('DELEGATION_PRINCIPLES', 'Delegation principles'), ('PRIORITIZATION', 'Prioritization'), ('PATIENT_EDUCATION', 'Patient education'), ('INTERPROFESSIONAL_COMMUNICATION', 'Interprofessional communication')], default='Hand hygiene', max_length=41)),
                ('sai', models.CharField(choices=[('SIMULATION_SAFE', 'Simulation safe'), ('ASSISTED_CLINICAL', 'Assisted clinical'), ('INDEPENDENT_CLINICAL', 'Independent clinical')], default='Simulation safe', max_length=20)),
                ('completed', models.DateField(default=datetime.date.today)),
                ('location', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('instructor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='instructor.instructor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
