# Generated by Django 5.2.10 on 2026-04-28 22:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentskill',
            unique_together={('student', 'skill')},
        ),
    ]
