# Generated by Django 5.2.10 on 2026-04-29 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_alter_instructor_courses'),
        ('skills', '0002_alter_studentskill_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSkillRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('NOT_PRACTICED', 'Not practiced'), ('SIMULATION_SAFE', 'Simulation safe'), ('ASSISTED_CLINICAL', 'Assisted clinical'), ('INDEPENDENT_CLINICAL', 'Independent clinical')], default='Not practiced', max_length=35)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='instructor.instructor')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
