# Generated by Django 6.0.2 on 2026-04-08 22:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_skill_studentskill_delete_skills'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentskill',
            unique_together={('student', 'skill', 'level')},
        ),
    ]
