# Generated by Django 6.0.1 on 2026-02-26 21:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourslog',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hourslog',
            name='instructor',
            field=models.CharField(default='admin', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hourslog',
            name='location',
            field=models.CharField(default='western', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hourslog',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hourslog',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
