# Generated by Django 6.0.2 on 2026-03-31 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hour', '0001_initial'),
        ('instructor', '0002_course_instructor_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hourslog',
            name='location',
        ),
        migrations.AddField(
            model_name='hourslog',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='instructor.course'),
            preserve_default=False,
        ),
    ]
