# Generated by Django 6.0.1 on 2026-02-27 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hour', '0002_hourslog_end_time_hourslog_instructor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hourslog',
            name='hours',
        ),
    ]
