# Generated by Django 6.0.1 on 2026-02-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hour', '0003_remove_hourslog_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourslog',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
