# Generated by Django 5.2.10 on 2026-04-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='courses',
            field=models.ManyToManyField(blank=True, to='instructor.course'),
        ),
    ]
