# Generated by Django 6.0.1 on 2026-02-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=300)),
                ('level', models.CharField(choices=[('s', 'S'), ('a', 'A'), ('i', 'I')])),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
