# Generated by Django 6.0.1 on 2026-02-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_skill_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(choices=[('s', 'S'), ('a', 'A'), ('i', 'I')], max_length=2),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.CheckConstraint(condition=models.Q(('level__in', ['s', 'a', 'i'])), name='level_val'),
        ),
    ]
